export type FeatureRisk = "low" | "medium" | "high" | "critical";

export interface FeatureDefinition {
  key: string;
  moduleKey: string;
  label: string;
  description: string;
  permissionKey: string;
  category: string;
  risk: FeatureRisk;
  navigationKey?: string;
  requires?: string[];
}

const f = (
  moduleKey: string,
  key: string,
  label: string,
  description: string,
  category: string,
  risk: FeatureRisk = "low",
  requires?: string[],
): FeatureDefinition => ({
  key,
  moduleKey,
  label,
  description,
  permissionKey: `${moduleKey}.${key}`,
  category,
  risk,
  requires,
});

export const FEATURE_CATALOG: FeatureDefinition[] = [
  // Dashboard
  f("dashboard", "view", "View Dashboard", "Access the business dashboard.", "overview"),
  f("dashboard", "sales", "View Sales Summary", "View sales KPIs and summaries.", "analytics"),
  f("dashboard", "purchases", "View Purchase Summary", "View purchase KPIs and summaries.", "analytics"),
  f("dashboard", "inventory", "View Inventory Summary", "View stock and inventory KPIs.", "analytics"),
  f("dashboard", "expenses", "View Expense Summary", "View expense KPIs and summaries.", "analytics"),
  f("dashboard", "profit", "View Profit Summary", "View profitability KPIs.", "analytics"),
  f("dashboard", "cash", "View Cash and Bank Summary", "View cash and bank position summaries.", "analytics"),
  f("dashboard", "low_stock", "View Low Stock Alerts", "View products that are below their stock thresholds.", "alerts"),
  f("dashboard", "receivables", "View Outstanding Receivables", "View outstanding customer balances.", "analytics"),
  f("dashboard", "payables", "View Outstanding Payables", "View outstanding supplier balances.", "analytics"),
  f("dashboard", "recent_transactions", "View Recent Transactions", "View recent business activity.", "activity"),
  f("dashboard", "kpis", "View Business KPIs", "View the full KPI panel.", "analytics"),

  // POS
  f("pos", "view", "Open POS", "Access the point-of-sale terminal.", "sales"),
  f("pos", "create_sale", "Create Sale", "Create a new POS sale.", "sales"),
  f("pos", "hold_sale", "Hold Sale", "Place a sale on hold.", "sales"),
  f("pos", "resume_sale", "Resume Held Sale", "Resume a previously held sale.", "sales"),
  f("pos", "edit_cart", "Edit Cart", "Change items and quantities in the active cart.", "sales"),
  f("pos", "apply_discount", "Apply Discount", "Apply an approved discount to a sale.", "pricing", "medium"),
  f("pos", "apply_line_discount", "Apply Line Discount", "Apply a discount to an individual line.", "pricing", "medium"),
  f("pos", "change_price", "Change Selling Price", "Override the configured selling price.", "pricing", "high"),
  f("pos", "void_sale", "Void Sale", "Void an active or completed sale where supported.", "controls", "high"),
  f("pos", "delete_cart", "Delete Cart", "Clear the current cart without completing the sale.", "sales"),
  f("pos", "suspend", "Suspend Transaction", "Suspend a transaction for later completion.", "sales"),
  f("pos", "reprint_receipt", "Reprint Receipt", "Reprint a POS receipt.", "receipts"),
  f("pos", "payment_cash", "Accept Cash", "Accept cash payments.", "payments"),
  f("pos", "payment_mobile_money", "Accept Mobile Money", "Accept mobile-money payments.", "payments"),
  f("pos", "payment_card", "Accept Card", "Accept card payments.", "payments"),
  f("pos", "payment_bank", "Accept Bank Payment", "Accept bank payments.", "payments"),
  f("pos", "payment_credit", "Accept Credit Sale", "Complete a sale on customer credit.", "payments", "medium"),
  f("pos", "split_payment", "Split Payment", "Accept a sale using multiple payment methods.", "payments"),
  f("pos", "change_payment_method", "Change Payment Method", "Change the payment method on an active transaction.", "payments", "medium"),
  f("pos", "refund", "Process Refund", "Refund a completed POS sale.", "refunds", "high"),
  f("pos", "open_till", "Open Till", "Open a cashier till.", "cash_control", "medium"),
  f("pos", "close_till", "Close Till", "Close and reconcile a cashier till.", "cash_control", "high"),
  f("pos", "view_till", "View Till Balance", "View current till totals.", "cash_control"),
  f("pos", "cash_in", "Cash In", "Record cash added to the till.", "cash_control", "medium"),
  f("pos", "cash_out", "Cash Out", "Record cash removed from the till.", "cash_control", "high"),
  f("pos", "reconcile_till", "Reconcile Till", "Reconcile expected and actual till balances.", "cash_control", "high"),
  f("pos", "override", "Override Transaction", "Perform privileged POS transaction overrides.", "controls", "critical"),
  f("pos", "select_customer", "Select Customer", "Attach a customer to a POS sale.", "customers"),
  f("pos", "create_customer", "Create Customer", "Create a customer from the POS.", "customers"),
  f("pos", "credit_sale", "Sell on Credit", "Complete a sale on customer credit.", "customers", "high"),

  // Sales
  f("sales", "view", "View Sales", "View sales records.", "sales"),
  f("sales", "create", "Create Sale", "Create a sale outside the POS.", "sales"),
  f("sales", "edit", "Edit Sale", "Edit an eligible sale.", "sales", "medium"),
  f("sales", "delete", "Delete Sale", "Delete an eligible sale record.", "sales", "high"),
  f("sales", "view_details", "View Sale Details", "View complete sale details.", "sales"),
  f("sales", "cancel", "Cancel Sale", "Cancel a completed or pending sale.", "controls", "high"),
  f("sales", "refund", "Refund Sale", "Refund a completed sale.", "refunds", "high"),
  f("sales", "credit", "Create Credit Sale", "Create a credit sale.", "credit", "medium"),
  f("sales", "record_payment", "Record Payment", "Record a customer payment.", "payments"),
  f("sales", "allocate_payment", "Allocate Payment", "Allocate a payment to invoices.", "payments", "medium"),
  f("sales", "view_payments", "View Customer Payments", "View customer payment history.", "payments"),
  f("sales", "print_invoice", "Print Invoice", "Print a sales invoice.", "documents"),
  f("sales", "email_invoice", "Email Invoice", "Send an invoice by email.", "documents"),
  f("sales", "export", "Export Sales", "Export sales records.", "export"),
  f("sales", "timeline", "View Sales Timeline", "View the lifecycle and audit timeline of sales.", "activity"),
  f("sales", "approve_discount", "Approve Discount", "Approve sales discounts.", "approvals", "high"),
  f("sales", "approve_refund", "Approve Refund", "Approve sales refunds.", "approvals", "critical"),
  f("sales", "approve_cancellation", "Approve Cancellation", "Approve sale cancellations.", "approvals", "high"),
  f("sales", "approve_price_override", "Approve Price Override", "Approve selling-price overrides.", "approvals", "critical"),

  // Products
  f("products", "view", "View Products", "View the product catalogue.", "catalog"),
  f("products", "view_details", "View Product Details", "View complete product details.", "catalog"),
  f("products", "create", "Create Product", "Create products.", "catalog"),
  f("products", "edit", "Edit Product", "Edit product information.", "catalog", "medium"),
  f("products", "delete", "Delete Product", "Delete products where allowed.", "catalog", "high"),
  f("products", "archive", "Archive Product", "Archive products without deleting history.", "catalog", "medium"),
  f("products", "restore", "Restore Product", "Restore archived products.", "catalog", "medium"),
  f("products", "import", "Import Products", "Bulk import products.", "catalog", "medium"),
  f("products", "export", "Export Products", "Export product records.", "export"),
  f("products", "create_category", "Create Category", "Create product categories.", "catalog"),
  f("products", "edit_category", "Edit Category", "Edit product categories.", "catalog", "medium"),
  f("products", "delete_category", "Delete Category", "Delete product categories.", "catalog", "high"),
  f("products", "manage_brands", "Manage Brands", "Manage product brands.", "catalog"),
  f("products", "manage_units", "Manage Units", "Manage product units of measure.", "catalog"),
  f("products", "manage_variants", "Manage Product Variants", "Manage product variants.", "catalog", "medium"),
  f("products", "manage_barcodes", "Manage Barcodes", "Manage product barcodes.", "catalog", "medium"),
  f("products", "manage_prices", "Manage Prices", "Manage selling prices.", "pricing", "high"),
  f("products", "manage_tax", "Manage Tax Rates", "Manage product tax configuration.", "tax", "high"),
  f("products", "manage_images", "Manage Product Images", "Manage product images.", "catalog"),
  f("products", "manage_batches", "Manage Product Batches", "Configure batch-tracked products.", "tracking", "medium"),
  f("products", "manage_expiry", "Manage Expiry Dates", "Configure expiry tracking.", "tracking", "medium"),
  f("products", "manage_serials", "Manage Serial Numbers", "Configure serial-number tracking.", "tracking", "medium"),
  f("products", "manage_composites", "Manage Composite Products", "Manage bundled or composite products.", "catalog", "high"),
  f("products", "manage_cost", "Manage Product Costs", "Manage product cost information.", "pricing", "high"),

  // Inventory
  f("inventory", "view", "View Inventory", "Access inventory records.", "stock"),
  f("inventory", "view_stock", "View Stock Levels", "View stock balances by location.", "stock"),
  f("inventory", "view_valuation", "View Stock Valuation", "View inventory valuation.", "valuation", "medium"),
  f("inventory", "view_movements", "View Stock Movement", "View stock movement history.", "stock"),
  f("inventory", "adjust", "Adjust Stock", "Create manual stock adjustments.", "stock_control", "high"),
  f("inventory", "approve_adjustment", "Approve Stock Adjustment", "Approve stock adjustments.", "approvals", "critical"),
  f("inventory", "transfer", "Transfer Stock", "Transfer stock between locations.", "stock_control", "high"),
  f("inventory", "approve_transfer", "Approve Stock Transfer", "Approve stock transfers.", "approvals", "high"),
  f("inventory", "receive", "Receive Stock", "Receive stock into inventory.", "receiving", "medium"),
  f("inventory", "issue", "Issue Stock", "Issue stock from inventory.", "stock_control", "high"),
  f("inventory", "writeoff", "Write Off Stock", "Write off damaged or lost stock.", "stock_control", "critical"),
  f("inventory", "count_create", "Create Stock Count", "Create stock-count sessions.", "stock_count"),
  f("inventory", "count_perform", "Perform Stock Count", "Enter physical stock counts.", "stock_count", "medium"),
  f("inventory", "count_approve", "Approve Stock Count", "Approve stock-count results.", "approvals", "high"),
  f("inventory", "view_variance", "View Stock Variances", "View count variances.", "stock_count", "medium"),
  f("inventory", "view_batches", "View Batches", "View batch records.", "tracking"),
  f("inventory", "manage_batches", "Manage Batches", "Manage inventory batches.", "tracking", "medium"),
  f("inventory", "view_expiry", "View Expiry", "View expiring inventory.", "tracking"),
  f("inventory", "manage_expiry", "Manage Expiry", "Manage expiry information.", "tracking", "medium"),

  // Purchases
  f("purchases", "view", "View Purchases", "View purchase transactions.", "purchases"),
  f("purchases", "create", "Create Purchase", "Create purchase documents.", "purchases"),
  f("purchases", "edit", "Edit Purchase", "Edit eligible purchase documents.", "purchases", "medium"),
  f("purchases", "delete", "Delete Purchase", "Delete eligible purchase documents.", "purchases", "high"),
  f("purchases", "approve", "Approve Purchase", "Approve purchase orders or bills.", "approvals", "high"),
  f("purchases", "receive", "Receive Purchase", "Receive purchased goods.", "receiving", "medium"),
  f("purchases", "cancel", "Cancel Purchase", "Cancel a purchase.", "controls", "high"),
  f("purchases", "return", "Return Purchase", "Return goods to a supplier.", "returns", "high"),
  f("purchases", "record_payment", "Record Supplier Payment", "Record payments to suppliers.", "payments", "medium"),
  f("purchases", "view_payments", "View Supplier Payments", "View supplier payment history.", "payments"),
  f("purchases", "print_po", "Print Purchase Order", "Print purchase orders.", "documents"),
  f("purchases", "export", "Export Purchases", "Export purchase records.", "export"),
  f("purchases", "history", "View Purchase History", "View purchase lifecycle history.", "activity"),

  // Expenses
  f("expenses", "view", "View Expenses", "View business expenses.", "expenses"),
  f("expenses", "create", "Create Expense", "Create an expense.", "expenses"),
  f("expenses", "edit", "Edit Expense", "Edit an expense.", "expenses", "medium"),
  f("expenses", "delete", "Delete Expense", "Delete an expense.", "expenses", "high"),
  f("expenses", "approve", "Approve Expense", "Approve submitted expenses.", "approvals", "high"),
  f("expenses", "reject", "Reject Expense", "Reject submitted expenses.", "approvals", "medium"),
  f("expenses", "record_payment", "Record Expense Payment", "Record payment of an expense.", "payments", "medium"),
  f("expenses", "view_categories", "View Expense Categories", "View expense categories.", "configuration"),
  f("expenses", "manage_categories", "Manage Expense Categories", "Create and edit expense categories.", "configuration", "medium"),
  f("expenses", "upload_receipt", "Upload Receipt", "Attach a receipt to an expense.", "documents"),
  f("expenses", "export", "Export Expenses", "Export expense records.", "export"),

  // Banking
  f("banking", "view", "View Bank Accounts", "View bank and cash accounts.", "accounts"),
  f("banking", "create_account", "Create Bank Account", "Create a bank account.", "accounts", "high"),
  f("banking", "edit_account", "Edit Bank Account", "Edit bank account configuration.", "accounts", "high"),
  f("banking", "delete_account", "Delete Bank Account", "Delete or deactivate a bank account.", "accounts", "critical"),
  f("banking", "view_transactions", "View Transactions", "View banking transactions.", "transactions"),
  f("banking", "deposit", "Record Deposit", "Record a deposit.", "transactions", "medium"),
  f("banking", "withdrawal", "Record Withdrawal", "Record a withdrawal.", "transactions", "high"),
  f("banking", "transfer", "Transfer Funds", "Transfer funds between accounts.", "transactions", "high"),
  f("banking", "bank_charge", "Record Bank Charge", "Record bank fees and charges.", "transactions", "medium"),
  f("banking", "reconcile", "Reconcile Account", "Reconcile a bank or cash account.", "reconciliation", "high"),
  f("banking", "import_statement", "Import Bank Statement", "Import external bank transactions.", "reconciliation", "high"),
  f("banking", "export", "Export Transactions", "Export banking transactions.", "export"),
  f("banking", "incoming_payments", "View Incoming Payments", "View incoming mobile-money or payment messages.", "incoming_payments"),
  f("banking", "match_payment", "Match Payment to Sale", "Match an incoming payment to a sale or invoice.", "incoming_payments", "high"),
  f("banking", "unmatch_payment", "Unmatch Payment", "Remove a payment-to-sale match.", "incoming_payments", "high"),
  f("banking", "approve_match", "Approve Payment Match", "Approve a payment match.", "approvals", "high"),
  f("banking", "view_payment_message", "View Payment Message", "View the original incoming payment message.", "incoming_payments", "medium"),

  // Accounting
  f("accounting", "view", "View Accounts", "View accounting accounts and balances.", "accounts"),
  f("accounting", "create_account", "Create Account", "Create a ledger account.", "accounts", "high"),
  f("accounting", "edit_account", "Edit Account", "Edit a ledger account.", "accounts", "high"),
  f("accounting", "disable_account", "Disable Account", "Disable a ledger account.", "accounts", "critical"),
  f("accounting", "general_ledger", "View General Ledger", "View posted ledger activity.", "reports"),
  f("accounting", "trial_balance", "View Trial Balance", "View the trial balance.", "reports"),
  f("accounting", "profit_loss", "View Profit and Loss", "View the profit and loss statement.", "reports"),
  f("accounting", "balance_sheet", "View Balance Sheet", "View the balance sheet.", "reports"),
  f("accounting", "cash_flow", "View Cash Flow", "View the cash flow statement.", "reports"),
  f("accounting", "financial_position", "View Financial Position", "View financial position information.", "reports"),
  f("accounting", "close_period", "Close Accounting Period", "Close an accounting period.", "period_control", "critical"),
  f("accounting", "reopen_period", "Reopen Accounting Period", "Reopen a closed accounting period.", "period_control", "critical"),
  f("accounting", "lock_transactions", "Lock Transactions", "Prevent posting into a locked period.", "period_control", "critical"),
  f("accounting", "manage_periods", "Manage Fiscal Periods", "Configure accounting periods.", "configuration", "high"),
  f("accounting", "manage_tax", "Manage Tax Accounts", "Configure tax accounts.", "configuration", "high"),
  f("accounting", "manage_currencies", "Manage Currencies", "Configure accounting currencies.", "configuration", "high"),
  f("accounting", "account_mapping", "Configure Account Mapping", "Configure automated account mappings.", "configuration", "critical"),

  // Manual journals
  f("manual_journals", "view", "View Journals", "View manual journals.", "journals"),
  f("manual_journals", "create", "Create Journal", "Create a manual journal entry.", "journals", "high"),
  f("manual_journals", "edit", "Edit Draft Journal", "Edit an unposted journal.", "journals", "high"),
  f("manual_journals", "delete", "Delete Draft Journal", "Delete an unposted journal.", "journals", "high"),
  f("manual_journals", "submit", "Submit Journal", "Submit a journal for approval.", "workflow", "high"),
  f("manual_journals", "approve", "Approve Journal", "Approve a manual journal.", "workflow", "critical"),
  f("manual_journals", "post", "Post Journal", "Post a journal to the ledger.", "workflow", "critical"),
  f("manual_journals", "reverse", "Reverse Journal", "Reverse a posted journal.", "workflow", "critical"),
  f("manual_journals", "view_posted", "View Posted Journals", "View posted journal entries.", "journals"),
  f("manual_journals", "export", "Export Journals", "Export journal entries.", "export"),

  // Reports
  f("reports", "sales", "Sales Report", "View sales reporting.", "sales"),
  f("reports", "sales_by_product", "Sales by Product", "Analyze sales by product.", "sales"),
  f("reports", "sales_by_customer", "Sales by Customer", "Analyze sales by customer.", "sales"),
  f("reports", "sales_by_cashier", "Sales by Cashier", "Analyze sales by cashier.", "sales", "medium"),
  f("reports", "sales_by_location", "Sales by Location", "Analyze sales by location.", "sales", "medium"),
  f("reports", "sales_by_payment", "Sales by Payment Method", "Analyze sales by payment method.", "sales"),
  f("reports", "stock", "Stock Report", "View stock reporting.", "inventory"),
  f("reports", "stock_movement", "Stock Movement", "View stock movement reporting.", "inventory", "medium"),
  f("reports", "stock_valuation", "Stock Valuation", "View inventory valuation reports.", "inventory", "high"),
  f("reports", "stock_adjustments", "Stock Adjustment Report", "View stock adjustment reporting.", "inventory", "high"),
  f("reports", "stock_transfers", "Stock Transfer Report", "View stock transfer reporting.", "inventory"),
  f("reports", "low_stock", "Low Stock Report", "View low-stock reporting.", "inventory"),
  f("reports", "expiry", "Expiry Report", "View expiry reporting.", "inventory"),
  f("reports", "purchases", "Purchase Report", "View purchase reporting.", "purchases"),
  f("reports", "purchases_by_supplier", "Purchases by Supplier", "Analyze purchases by supplier.", "purchases"),
  f("reports", "purchase_returns", "Purchase Returns", "View purchase-return reporting.", "purchases"),
  f("reports", "profit_loss", "Profit and Loss", "View profit and loss reporting.", "financial"),
  f("reports", "balance_sheet", "Balance Sheet", "View balance-sheet reporting.", "financial"),
  f("reports", "trial_balance", "Trial Balance", "View trial-balance reporting.", "financial"),
  f("reports", "general_ledger", "General Ledger", "View general-ledger reporting.", "financial"),
  f("reports", "expenses", "Expense Report", "View expense reporting.", "financial"),
  f("reports", "cash_flow", "Cash Flow", "View cash-flow reporting.", "financial"),
  f("reports", "tax", "Tax Report", "View tax reporting.", "financial", "medium"),
  f("reports", "export", "Export Reports", "Export reports and datasets.", "export", "medium"),
  f("reports", "schedule", "Schedule Reports", "Schedule recurring report delivery.", "automation", "medium"),

  // Settings
  f("settings", "business_view", "View Business Settings", "View business configuration.", "business"),
  f("settings", "business_edit", "Edit Business Details", "Edit business identity and details.", "business", "high"),
  f("settings", "logo", "Manage Logo", "Manage business branding.", "business"),
  f("settings", "tax", "Manage Tax Settings", "Manage business tax configuration.", "tax", "high"),
  f("settings", "currency", "Manage Currency", "Manage business currency settings.", "business", "critical"),
  f("settings", "timezone", "Manage Timezone", "Manage business timezone.", "business", "high"),
  f("settings", "theme", "Manage Business Theme", "Manage business theme and branding.", "business"),
  f("settings", "locations_view", "View Locations", "View business locations.", "locations"),
  f("settings", "locations_create", "Create Location", "Create a business location.", "locations", "high"),
  f("settings", "locations_edit", "Edit Location", "Edit a business location.", "locations", "high"),
  f("settings", "locations_disable", "Disable Location", "Disable a business location.", "locations", "critical"),
  f("settings", "users_view", "View Users", "View business users.", "users"),
  f("settings", "users_invite", "Invite User", "Invite a user to the business.", "users", "high"),
  f("settings", "users_edit", "Edit User", "Edit user details.", "users", "high"),
  f("settings", "users_disable", "Disable User", "Disable a user.", "users", "critical"),
  f("settings", "assign_role", "Assign Role", "Assign a role to a user.", "users", "critical"),
  f("settings", "assign_location", "Assign Location", "Assign a user to a location.", "users", "high"),
  f("settings", "reset_access", "Reset User Access", "Reset a user's access configuration.", "users", "critical"),
  f("settings", "roles_view", "View Roles", "View business roles.", "roles"),
  f("settings", "roles_create", "Create Role", "Create a custom role.", "roles", "critical"),
  f("settings", "roles_edit", "Edit Role", "Edit a custom role.", "roles", "critical"),
  f("settings", "roles_delete", "Delete Role", "Delete a custom role.", "roles", "critical"),
  f("settings", "permissions_manage", "Manage Permissions", "Grant or revoke role permissions.", "roles", "critical"),
  f("settings", "pos", "Configure POS", "Configure POS behavior.", "pos", "high"),
  f("settings", "payment_methods", "Configure Payment Methods", "Configure accepted payment methods.", "pos", "high"),
  f("settings", "receipt", "Configure Receipt", "Configure receipt layout and behavior.", "pos", "medium"),
  f("settings", "numbering", "Configure Invoice Numbering", "Configure document numbering.", "documents", "high"),
  f("settings", "discounts", "Configure Discounts", "Configure discount rules.", "pricing", "high"),
  f("settings", "audit_log", "View Audit Log", "View business audit history.", "audit", "medium"),
  f("settings", "audit_export", "Export Audit Log", "Export audit history.", "audit", "high"),

  // Profile
  f("profile", "view", "View Profile", "View your own profile.", "profile"),
  f("profile", "edit", "Edit Profile", "Edit your own profile.", "profile"),
  f("profile", "edit_name", "Change Name", "Change your display name.", "profile"),
  f("profile", "edit_phone", "Change Phone", "Change your phone number.", "profile"),
  f("profile", "avatar", "Change Avatar", "Change your profile avatar.", "profile"),
  f("profile", "password", "Change Password", "Change your account password.", "security", "high"),
  f("profile", "preferences", "Manage Preferences", "Manage personal application preferences.", "profile"),
  f("profile", "notifications", "Manage Notifications", "Manage personal notification preferences.", "profile"),
];

export const FEATURE_KEYS = FEATURE_CATALOG.map((feature) => feature.permissionKey);

export const FEATURES_BY_MODULE = Object.fromEntries(
  [...new Set(FEATURE_CATALOG.map((feature) => feature.moduleKey))].map((moduleKey) => [
    moduleKey,
    FEATURE_CATALOG.filter((feature) => feature.moduleKey === moduleKey),
  ]),
) as Record<string, FeatureDefinition[]>;

export function getFeaturesForModule(moduleKey: string): FeatureDefinition[] {
  return FEATURES_BY_MODULE[moduleKey] ?? [];
}

export function getFeature(permissionKey: string): FeatureDefinition | undefined {
  return FEATURE_CATALOG.find((feature) => feature.permissionKey === permissionKey);
}
