import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useServerFn } from '@tanstack/react-start';
import { queueEnterpriseBackup, requestTenantArchive, queueSystemJob, recordDrEvent, exportTenantControlPlane } from '@/lib/superAdminEnterprise.functions';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Archive, DatabaseBackup, Download, HardDrive, Play, RefreshCw, ShieldCheck, Timer, Workflow, AlertTriangle } from 'lucide-react';
import { formatDistanceToNow } from 'date-fns';
import { toast } from 'sonner';

export default function SuperAdminEnterprise() {
  const backup = useServerFn(queueEnterpriseBackup); const archive = useServerFn(requestTenantArchive); const runJob = useServerFn(queueSystemJob); const drEvent = useServerFn(recordDrEvent); const exportTenant = useServerFn(exportTenantControlPlane);
  const [backups,setBackups]=useState<any[]>([]); const [policies,setPolicies]=useState<any[]>([]); const [archives,setArchives]=useState<any[]>([]); const [jobs,setJobs]=useState<any[]>([]); const [plans,setPlans]=useState<any[]>([]); const [events,setEvents]=useState<any[]>([]); const [tenants,setTenants]=useState<any[]>([]); const [selectedTenant,setSelectedTenant]=useState(''); const [reason,setReason]=useState(''); const [busy,setBusy]=useState(false);
  const load=async()=>{const [b,p,a,j,d,e,t]=await Promise.all([supabase.from('platform_backups').select('*').order('created_at',{ascending:false}).limit(20),supabase.from('data_retention_policies').select('*').order('scope'),supabase.from('tenant_archives').select('*,businesses(name)').order('requested_at',{ascending:false}).limit(20),supabase.from('system_jobs').select('*').order('label'),supabase.from('dr_plans').select('*').order('created_at'),supabase.from('dr_events').select('*,dr_plans(name)').order('created_at',{ascending:false}).limit(20),supabase.from('businesses').select('id,name,is_active').order('name').limit(200)]);setBackups(b.data||[]);setPolicies(p.data||[]);setArchives(a.data||[]);setJobs(j.data||[]);setPlans(d.data||[]);setEvents(e.data||[]);setTenants(t.data||[]);};
  useEffect(()=>{void load()},[]);
  const currentPlan=plans[0];
  const queueBackup=async()=>{setBusy(true);try{await backup({data:{backupType:'manual'}});toast.success('Backup queued');await load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
  const requestArchive=async()=>{if(!selectedTenant||!reason.trim())return toast.error('Select a tenant and enter a reason');setBusy(true);try{await archive({data:{businessId:selectedTenant,reason,archiveType:'logical'}});toast.success('Archive request created');setReason('');await load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
  const doExport=async()=>{if(!selectedTenant)return toast.error('Select a tenant');setBusy(true);try{const payload=await exportTenant({data:{businessId:selectedTenant}});const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`tenant-export-${selectedTenant}.json`;a.click();URL.revokeObjectURL(a.href);toast.success('Tenant export downloaded')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
  const run=async(key:string)=>{setBusy(true);try{await runJob({data:{jobKey:key}});toast.success('Job queued');await load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
  const drill=async()=>{if(!currentPlan)return;setBusy(true);try{await drEvent({data:{planId:currentPlan.id,eventType:'drill',description:'Disaster recovery restore drill initiated from Super Admin'}});toast.success('DR drill recorded');await load()}catch(e:any){toast.error(e.message)}finally{setBusy(false)}};
  const statusClass=(s:string)=>s==='completed'||s==='verified'||s==='passed'||s==='ready'?'default':s==='failed'||s==='at_risk'?'destructive':'secondary';
  return <div className="space-y-6">
    <div className="flex items-start justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">Enterprise Controls</h1><p className="text-sm text-muted-foreground mt-1">Backups, retention, tenant lifecycle, system jobs and disaster recovery.</p></div><Button variant="outline" onClick={()=>void load()}><RefreshCw className="h-4 w-4 mr-2"/>Refresh</Button></div>
    <Card className="border-amber-200 bg-amber-50/60 dark:border-amber-900 dark:bg-amber-950/20 p-4"><div className="flex gap-3"><AlertTriangle className="h-5 w-5 text-amber-600 mt-0.5"/><div className="text-sm"><div className="font-semibold">Control plane notice</div><div className="text-muted-foreground mt-1">These controls queue and record enterprise operations. Physical database backups, deletion and failover execution must be handled by the configured infrastructure worker/provider.</div></div></div></Card>
    <Tabs defaultValue="backups"><TabsList className="grid w-full grid-cols-2 md:grid-cols-5"><TabsTrigger value="backups">Backups</TabsTrigger><TabsTrigger value="retention">Retention</TabsTrigger><TabsTrigger value="tenants">Tenant Archive</TabsTrigger><TabsTrigger value="jobs">System Jobs</TabsTrigger><TabsTrigger value="dr">Disaster Recovery</TabsTrigger></TabsList>
      <TabsContent value="backups" className="space-y-4"><div className="grid gap-4 md:grid-cols-3"><Card className="p-5"><div className="flex items-center gap-3"><DatabaseBackup className="h-5 w-5 text-primary"/><div><div className="text-xs text-muted-foreground">Latest backup</div><div className="font-semibold mt-1">{backups[0]?formatDistanceToNow(new Date(backups[0].created_at),{addSuffix:true}):'No records'}</div></div></div></Card><Card className="p-5"><div className="flex items-center gap-3"><HardDrive className="h-5 w-5 text-primary"/><div><div className="text-xs text-muted-foreground">Verified backups</div><div className="font-semibold mt-1">{backups.filter(b=>b.status==='verified').length}</div></div></div></Card><Card className="p-5 flex items-center justify-between"><div><div className="font-semibold">Run backup</div><div className="text-xs text-muted-foreground mt-1">Queue a manual backup job.</div></div><Button onClick={()=>void queueBackup()} disabled={busy}><DatabaseBackup className="h-4 w-4 mr-2"/>Queue</Button></Card></div><Card><div className="p-5 border-b font-semibold">Backup history</div><div className="divide-y">{backups.map(b=><div key={b.id} className="p-4 flex justify-between gap-4"><div><div className="font-medium">{b.backup_type} backup</div><div className="text-xs text-muted-foreground mt-1">{new Date(b.created_at).toLocaleString()} · {b.provider}</div></div><Badge variant={statusClass(b.status) as any}>{b.status}</Badge></div>)}{!backups.length&&<div className="p-8 text-center text-sm text-muted-foreground">No backup records yet.</div>}</div></Card></TabsContent>
      <TabsContent value="retention" className="space-y-4"><Card><div className="p-5 border-b"><div className="font-semibold">Data retention policies</div><div className="text-xs text-muted-foreground mt-1">Review retention windows and enforcement actions.</div></div><div className="divide-y">{policies.map(p=><div key={p.id} className="p-4 flex items-center justify-between gap-4"><div><div className="font-medium">{p.resource_key}</div><div className="text-xs text-muted-foreground mt-1">{p.scope}{p.business_id?' · tenant scoped':''} · {p.retention_days} days</div></div><div className="flex items-center gap-2"><Badge variant="outline">{p.action}</Badge><Badge variant={p.enabled?'default':'secondary'}>{p.enabled?'Enabled':'Paused'}</Badge></div></div>)}{!policies.length&&<div className="p-8 text-center text-sm text-muted-foreground">No retention policies configured.</div>}</div></Card></TabsContent>
      <TabsContent value="tenants" className="space-y-4"><Card className="p-5 space-y-4"><div><Label>Tenant</Label><Select value={selectedTenant} onValueChange={setSelectedTenant}><SelectTrigger className="mt-2"><SelectValue placeholder="Select a tenant"/></SelectTrigger><SelectContent>{tenants.map(t=><SelectItem key={t.id} value={t.id}>{t.name}{!t.is_active?' · suspended':''}</SelectItem>)}</SelectContent></Select></div><div><Label>Reason</Label><Input className="mt-2" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Why is this tenant being archived?"/></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={()=>void doExport()} disabled={busy||!selectedTenant}><Download className="h-4 w-4 mr-2"/>Export tenant</Button><Button variant="destructive" onClick={()=>void requestArchive()} disabled={busy||!selectedTenant}><Archive className="h-4 w-4 mr-2"/>Request archive</Button></div></Card><Card><div className="p-5 border-b font-semibold">Archive requests</div><div className="divide-y">{archives.map(a=><div key={a.id} className="p-4 flex justify-between gap-4"><div><div className="font-medium">{a.businesses?.name||a.business_id}</div><div className="text-xs text-muted-foreground mt-1">{a.reason} · {formatDistanceToNow(new Date(a.requested_at),{addSuffix:true})}</div></div><Badge variant={statusClass(a.status) as any}>{a.status}</Badge></div>)}{!archives.length&&<div className="p-8 text-center text-sm text-muted-foreground">No archive requests.</div>}</div></Card></TabsContent>
      <TabsContent value="jobs" className="space-y-4"><div className="grid gap-3">{jobs.map(j=><Card key={j.id} className="p-4 flex items-center justify-between gap-4"><div className="flex items-center gap-3"><Workflow className="h-5 w-5 text-primary"/><div><div className="font-semibold">{j.label}</div><div className="text-xs text-muted-foreground mt-1">{j.schedule||'On demand'}{j.last_finished_at?` · Last run ${formatDistanceToNow(new Date(j.last_finished_at),{addSuffix:true})}`:''}</div></div></div><div className="flex items-center gap-2"><Badge variant={statusClass(j.status) as any}>{j.status}</Badge><Button size="sm" variant="outline" onClick={()=>void run(j.job_key)} disabled={busy||j.status==='running'}><Play className="h-3.5 w-3.5 mr-1.5"/>Run now</Button></div></Card>)}</div></TabsContent>
      <TabsContent value="dr" className="space-y-4"><Card className="p-5"><div className="flex items-start justify-between gap-4"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 text-primary mt-0.5"/><div><div className="font-semibold">{currentPlan?.name||'DR plan'}</div><div className="text-sm text-muted-foreground mt-1">RPO {currentPlan?.rpo_minutes||'—'} min · RTO {currentPlan?.rto_minutes||'—'} min</div><div className="text-xs text-muted-foreground mt-2">{currentPlan?.primary_region||'Primary'} → {currentPlan?.secondary_region||'Secondary'}</div></div></div><Button onClick={()=>void drill()} disabled={busy||!currentPlan}><Timer className="h-4 w-4 mr-2"/>Record restore drill</Button></div></Card><Card><div className="p-5 border-b font-semibold">DR activity</div><div className="divide-y">{events.map(e=><div key={e.id} className="p-4 flex justify-between gap-4"><div><div className="font-medium">{e.event_type.replace('_',' ')}</div><div className="text-xs text-muted-foreground mt-1">{e.description} · {formatDistanceToNow(new Date(e.created_at),{addSuffix:true})}</div></div><Badge variant={statusClass(e.status) as any}>{e.status}</Badge></div>)}{!events.length&&<div className="p-8 text-center text-sm text-muted-foreground">No DR events recorded.</div>}</div></Card></TabsContent>
    </Tabs>
  </div>;
}
