import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useServerFn } from '@tanstack/react-start';
import { createSupportSession } from '@/lib/superAdminPhase2.functions';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Headset, Search, ExternalLink, ShieldAlert } from 'lucide-react';
import { toast } from 'sonner';

export default function SuperAdminSupport(){const [q,setQ]=useState('');const [tenants,setTenants]=useState<any[]>([]);const [busy,setBusy]=useState<string|null>(null);const call=useServerFn(createSupportSession);useEffect(()=>{(async()=>{const {data}=await supabase.from('businesses').select('id,name,is_active,created_at,owner_id').order('name').limit(100);setTenants(data||[]);})();},[]);const filtered=tenants.filter(t=>t.name?.toLowerCase().includes(q.toLowerCase()));const start=async(id:string)=>{setBusy(id);try{const r=await call({data:{business_id:id}});window.open((r as any).actionLink,'_blank','noopener,noreferrer');toast.success('Support session opened in a new tab');}catch(e:any){toast.error(e?.message||'Could not start support session');}finally{setBusy(null);}};return <div className="space-y-6"><div><h1 className="text-2xl font-bold tracking-tight">Support & Impersonation</h1><p className="text-sm text-muted-foreground mt-1">Open a controlled tenant-owner session for troubleshooting. Every session is audit logged.</p></div><Card className="border-amber-200 bg-amber-50/60 dark:border-amber-900 dark:bg-amber-950/20 p-4"><div className="flex gap-3"><ShieldAlert className="h-5 w-5 text-amber-600 mt-0.5"/><div className="text-sm"><div className="font-semibold">Use only for customer support</div><div className="text-muted-foreground mt-1">The new tab authenticates as the tenant owner. Do not perform financial, destructive, or security-sensitive actions without customer authorization.</div></div></div></Card><Card className="p-4"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tenants…" className="pl-9"/></div></Card><div className="grid gap-3">{filtered.map(t=><Card key={t.id} className="p-4"><div className="flex items-center justify-between gap-4"><div className="flex items-center gap-3"><div className="h-10 w-10 rounded-lg bg-primary/10 flex items-center justify-center"><Headset className="h-4 w-4 text-primary"/></div><div><div className="font-semibold">{t.name}</div><div className="text-xs text-muted-foreground mt-1">Tenant ID: {t.id}</div></div></div><div className="flex items-center gap-2"><Badge variant={t.is_active?'outline':'secondary'}>{t.is_active?'Active':'Suspended'}</Badge><Button size="sm" onClick={()=>void start(t.id)} disabled={busy===t.id||!t.is_active}><ExternalLink className="h-3.5 w-3.5 mr-1.5"/>{busy===t.id?'Opening…':'Open support session'}</Button></div></div></Card>)}</div></div>}
