import { useEffect, useMemo, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { DollarSign, TrendingUp, Users, CreditCard } from 'lucide-react';
import { format, startOfMonth, subMonths } from 'date-fns';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';

export default function SuperAdminRevenue(){
 const [payments,setPayments]=useState<any[]>([]); const [subs,setSubs]=useState<any[]>([]); const [plans,setPlans]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const [p,s,pl]=await Promise.all([supabase.from('offline_payment_requests').select('amount_kes,status,created_at').eq('status','approved'),supabase.from('subscriptions').select('status,product_id,current_period_end'),supabase.from('subscription_packages').select('id,name,monthly_price_kes,yearly_price_kes')]);setPayments(p.data||[]);setSubs(s.data||[]);setPlans(pl.data||[]);setLoading(false);})();},[]);
 const total=payments.reduce((s,p)=>s+Number(p.amount_kes||0),0); const monthStart=startOfMonth(new Date()); const monthly=payments.filter(p=>new Date(p.created_at)>=monthStart).reduce((s,p)=>s+Number(p.amount_kes||0),0); const active=subs.filter(s=>s.status==='active').length; const mrr=subs.filter(s=>s.status==='active').reduce((sum,s)=>{const p=plans.find(x=>x.id===s.product_id);return sum+Number(p?.monthly_price_kes||0)},0);
 const trend=useMemo(()=>{const map=new Map<string,number>();for(let i=5;i>=0;i--){map.set(format(startOfMonth(subMonths(new Date(),i)),'MMM'),0)}payments.forEach(p=>{const k=format(new Date(p.created_at),'MMM');if(map.has(k))map.set(k,(map.get(k)||0)+Number(p.amount_kes||0));});return Array.from(map,([month,revenue])=>({month,revenue}));},[payments]);
 const fmt=(n:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:0}).format(n);
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold tracking-tight">Billing & Revenue</h1><p className="text-sm text-muted-foreground mt-1">Platform revenue, MRR and subscription performance.</p></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[[DollarSign,'Collected',fmt(total)],[CreditCard,'This month',fmt(monthly)],[TrendingUp,'MRR',fmt(mrr)],[Users,'Active subscriptions',active]].map(([Icon,label,value]:any)=><Card key={label} className="p-5"><div className="flex items-center gap-3"><div className="h-9 w-9 rounded-lg bg-primary/10 flex items-center justify-center"><Icon className="h-4 w-4 text-primary"/></div><div><div className="text-xs text-muted-foreground">{label}</div><div className="text-xl font-bold mt-1">{loading?'—':value}</div></div></div></Card>)}</div><Card className="p-5"><div className="flex items-center justify-between mb-4"><div><h2 className="font-semibold">Revenue trend</h2><p className="text-xs text-muted-foreground">Approved offline payments, last 6 months.</p></div><Badge variant="outline">KES</Badge></div><div className="h-[280px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3" className="stroke-muted"/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={(v:any)=>fmt(Number(v))}/><Area type="monotone" dataKey="revenue" fill="hsl(var(--primary) / .14)" stroke="hsl(var(--primary))" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Card></div>;
}
