/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SuperRouteImport } from './routes/_super'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppBankingRouteImport } from './routes/_app.banking'
import { Route as AppBarcodeMappingRouteImport } from './routes/_app.barcode-mapping'
import { Route as AppChartOfAccountsRouteImport } from './routes/_app.chart-of-accounts'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppHrRouteImport } from './routes/_app.hr'
import { Route as AppInventoryRouteImport } from './routes/_app.inventory'
import { Route as AppJournalEntriesRouteImport } from './routes/_app.journal-entries'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppProductsRouteImport } from './routes/_app.products'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRolesRouteImport } from './routes/_app.roles'
import { Route as AppSalesRouteImport } from './routes/_app.sales'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppTaxComplianceRouteImport } from './routes/_app.tax-compliance'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as SuperAdminLoginRouteImport } from './routes/super-admin.login'
import { Route as AppPurchasesIndexRouteImport } from './routes/_app.purchases.index'
import { Route as AppPurchasesNewRouteImport } from './routes/_app.purchases.new'
import { Route as SuperSuperAdminIndexRouteImport } from './routes/_super.super-admin.index'
import { Route as SuperSuperAdminActivityRouteImport } from './routes/_super.super-admin.activity'
import { Route as SuperSuperAdminLandingRouteImport } from './routes/_super.super-admin.landing'
import { Route as SuperSuperAdminModulesRouteImport } from './routes/_super.super-admin.modules'
import { Route as SuperSuperAdminNotificationsRouteImport } from './routes/_super.super-admin.notifications'
import { Route as SuperSuperAdminPaymentsRouteImport } from './routes/_super.super-admin.payments'
import { Route as SuperSuperAdminSubscriptionsRouteImport } from './routes/_super.super-admin.subscriptions'
import { Route as SuperSuperAdminTenantApprovalsRouteImport } from './routes/_super.super-admin.tenant-approvals'
import { Route as SuperSuperAdminUsersRouteImport } from './routes/_super.super-admin.users'
import { Route as AppPurchasesIdEditRouteImport } from './routes/_app.purchases.$id.edit'
import { Route as SuperSuperAdminBusinessesIndexRouteImport } from './routes/_super.super-admin.businesses.index'
import { Route as SuperSuperAdminCmsCtaRouteImport } from './routes/_super.super-admin.cms.cta'
import { Route as SuperSuperAdminCmsFaqRouteImport } from './routes/_super.super-admin.cms.faq'
import { Route as SuperSuperAdminCmsFeaturesRouteImport } from './routes/_super.super-admin.cms.features'
import { Route as SuperSuperAdminCmsHeroRouteImport } from './routes/_super.super-admin.cms.hero'
import { Route as SuperSuperAdminCmsHowItWorksRouteImport } from './routes/_super.super-admin.cms.how-it-works'
import { Route as SuperSuperAdminCmsPricingRouteImport } from './routes/_super.super-admin.cms.pricing'
import { Route as SuperSuperAdminCmsStatsRouteImport } from './routes/_super.super-admin.cms.stats'
import { Route as SuperSuperAdminCmsTestimonialsRouteImport } from './routes/_super.super-admin.cms.testimonials'
import { Route as SuperSuperAdminPackagesIndexRouteImport } from './routes/_super.super-admin.packages.index'
import { Route as SuperSuperAdminPackagesNewRouteImport } from './routes/_super.super-admin.packages.new'
import { Route as SuperSuperAdminSettingsIndexRouteImport } from './routes/_super.super-admin.settings.index'
import { Route as SuperSuperAdminBusinessesIdIndexRouteImport } from './routes/_super.super-admin.businesses.$id.index'
import { Route as SuperSuperAdminBusinessesIdEditRouteImport } from './routes/_super.super-admin.businesses.$id.edit'
import { Route as SuperSuperAdminPackagesIdEditRouteImport } from './routes/_super.super-admin.packages.$id.edit'
import { Route as SuperSuperAdminSettingsPaymentsMpesaRouteImport } from './routes/_super.super-admin.settings.payments.mpesa'
import { Route as SuperSuperAdminSettingsPaymentsPaystackRouteImport } from './routes/_super.super-admin.settings.payments.paystack'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperRoute = SuperRouteImport.update({
  id: '/_super',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBankingRoute = AppBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AppRoute,
} as any)
const AppBarcodeMappingRoute = AppBarcodeMappingRouteImport.update({
  id: '/barcode-mapping',
  path: '/barcode-mapping',
  getParentRoute: () => AppRoute,
} as any)
const AppChartOfAccountsRoute = AppChartOfAccountsRouteImport.update({
  id: '/chart-of-accounts',
  path: '/chart-of-accounts',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppHrRoute = AppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalEntriesRoute = AppJournalEntriesRouteImport.update({
  id: '/journal-entries',
  path: '/journal-entries',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRolesRoute = AppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesRoute = AppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxComplianceRoute = AppTaxComplianceRouteImport.update({
  id: '/tax-compliance',
  path: '/tax-compliance',
  getParentRoute: () => AppRoute,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminLoginRoute = SuperAdminLoginRouteImport.update({
  id: '/super-admin/login',
  path: '/super-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPurchasesIndexRoute = AppPurchasesIndexRouteImport.update({
  id: '/purchases/',
  path: '/purchases/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesNewRoute = AppPurchasesNewRouteImport.update({
  id: '/purchases/new',
  path: '/purchases/new',
  getParentRoute: () => AppRoute,
} as any)
const SuperSuperAdminIndexRoute = SuperSuperAdminIndexRouteImport.update({
  id: '/super-admin/',
  path: '/super-admin/',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminActivityRoute = SuperSuperAdminActivityRouteImport.update({
  id: '/super-admin/activity',
  path: '/super-admin/activity',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminLandingRoute = SuperSuperAdminLandingRouteImport.update({
  id: '/super-admin/landing',
  path: '/super-admin/landing',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminModulesRoute = SuperSuperAdminModulesRouteImport.update({
  id: '/super-admin/modules',
  path: '/super-admin/modules',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminNotificationsRoute =
  SuperSuperAdminNotificationsRouteImport.update({
    id: '/super-admin/notifications',
    path: '/super-admin/notifications',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminPaymentsRoute = SuperSuperAdminPaymentsRouteImport.update({
  id: '/super-admin/payments',
  path: '/super-admin/payments',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminSubscriptionsRoute =
  SuperSuperAdminSubscriptionsRouteImport.update({
    id: '/super-admin/subscriptions',
    path: '/super-admin/subscriptions',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminTenantApprovalsRoute =
  SuperSuperAdminTenantApprovalsRouteImport.update({
    id: '/super-admin/tenant-approvals',
    path: '/super-admin/tenant-approvals',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminUsersRoute = SuperSuperAdminUsersRouteImport.update({
  id: '/super-admin/users',
  path: '/super-admin/users',
  getParentRoute: () => SuperRoute,
} as any)
const AppPurchasesIdEditRoute = AppPurchasesIdEditRouteImport.update({
  id: '/purchases/$id/edit',
  path: '/purchases/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const SuperSuperAdminBusinessesIndexRoute =
  SuperSuperAdminBusinessesIndexRouteImport.update({
    id: '/super-admin/businesses/',
    path: '/super-admin/businesses/',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminCmsCtaRoute = SuperSuperAdminCmsCtaRouteImport.update({
  id: '/super-admin/cms/cta',
  path: '/super-admin/cms/cta',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminCmsFaqRoute = SuperSuperAdminCmsFaqRouteImport.update({
  id: '/super-admin/cms/faq',
  path: '/super-admin/cms/faq',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminCmsFeaturesRoute =
  SuperSuperAdminCmsFeaturesRouteImport.update({
    id: '/super-admin/cms/features',
    path: '/super-admin/cms/features',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminCmsHeroRoute = SuperSuperAdminCmsHeroRouteImport.update({
  id: '/super-admin/cms/hero',
  path: '/super-admin/cms/hero',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminCmsHowItWorksRoute =
  SuperSuperAdminCmsHowItWorksRouteImport.update({
    id: '/super-admin/cms/how-it-works',
    path: '/super-admin/cms/how-it-works',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminCmsPricingRoute =
  SuperSuperAdminCmsPricingRouteImport.update({
    id: '/super-admin/cms/pricing',
    path: '/super-admin/cms/pricing',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminCmsStatsRoute = SuperSuperAdminCmsStatsRouteImport.update({
  id: '/super-admin/cms/stats',
  path: '/super-admin/cms/stats',
  getParentRoute: () => SuperRoute,
} as any)
const SuperSuperAdminCmsTestimonialsRoute =
  SuperSuperAdminCmsTestimonialsRouteImport.update({
    id: '/super-admin/cms/testimonials',
    path: '/super-admin/cms/testimonials',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminPackagesIndexRoute =
  SuperSuperAdminPackagesIndexRouteImport.update({
    id: '/super-admin/packages/',
    path: '/super-admin/packages/',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminPackagesNewRoute =
  SuperSuperAdminPackagesNewRouteImport.update({
    id: '/super-admin/packages/new',
    path: '/super-admin/packages/new',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminSettingsIndexRoute =
  SuperSuperAdminSettingsIndexRouteImport.update({
    id: '/super-admin/settings/',
    path: '/super-admin/settings/',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminBusinessesIdIndexRoute =
  SuperSuperAdminBusinessesIdIndexRouteImport.update({
    id: '/super-admin/businesses/$id/',
    path: '/super-admin/businesses/$id/',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminBusinessesIdEditRoute =
  SuperSuperAdminBusinessesIdEditRouteImport.update({
    id: '/super-admin/businesses/$id/edit',
    path: '/super-admin/businesses/$id/edit',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminPackagesIdEditRoute =
  SuperSuperAdminPackagesIdEditRouteImport.update({
    id: '/super-admin/packages/$id/edit',
    path: '/super-admin/packages/$id/edit',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminSettingsPaymentsMpesaRoute =
  SuperSuperAdminSettingsPaymentsMpesaRouteImport.update({
    id: '/super-admin/settings/payments/mpesa',
    path: '/super-admin/settings/payments/mpesa',
    getParentRoute: () => SuperRoute,
  } as any)
const SuperSuperAdminSettingsPaymentsPaystackRoute =
  SuperSuperAdminSettingsPaymentsPaystackRouteImport.update({
    id: '/super-admin/settings/payments/paystack',
    path: '/super-admin/settings/payments/paystack',
    getParentRoute: () => SuperRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/banking': typeof AppBankingRoute
  '/barcode-mapping': typeof AppBarcodeMappingRoute
  '/chart-of-accounts': typeof AppChartOfAccountsRoute
  '/customers': typeof AppCustomersRoute
  '/expenses': typeof AppExpensesRoute
  '/hr': typeof AppHrRoute
  '/inventory': typeof AppInventoryRoute
  '/journal-entries': typeof AppJournalEntriesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/tax-compliance': typeof AppTaxComplianceRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/super-admin/activity': typeof SuperSuperAdminActivityRoute
  '/super-admin/landing': typeof SuperSuperAdminLandingRoute
  '/super-admin/modules': typeof SuperSuperAdminModulesRoute
  '/super-admin/notifications': typeof SuperSuperAdminNotificationsRoute
  '/super-admin/payments': typeof SuperSuperAdminPaymentsRoute
  '/super-admin/subscriptions': typeof SuperSuperAdminSubscriptionsRoute
  '/super-admin/tenant-approvals': typeof SuperSuperAdminTenantApprovalsRoute
  '/super-admin/users': typeof SuperSuperAdminUsersRoute
  '/purchases/': typeof AppPurchasesIndexRoute
  '/super-admin/': typeof SuperSuperAdminIndexRoute
  '/purchases/$id/edit': typeof AppPurchasesIdEditRoute
  '/super-admin/cms/cta': typeof SuperSuperAdminCmsCtaRoute
  '/super-admin/cms/faq': typeof SuperSuperAdminCmsFaqRoute
  '/super-admin/cms/features': typeof SuperSuperAdminCmsFeaturesRoute
  '/super-admin/cms/hero': typeof SuperSuperAdminCmsHeroRoute
  '/super-admin/cms/how-it-works': typeof SuperSuperAdminCmsHowItWorksRoute
  '/super-admin/cms/pricing': typeof SuperSuperAdminCmsPricingRoute
  '/super-admin/cms/stats': typeof SuperSuperAdminCmsStatsRoute
  '/super-admin/cms/testimonials': typeof SuperSuperAdminCmsTestimonialsRoute
  '/super-admin/packages/new': typeof SuperSuperAdminPackagesNewRoute
  '/super-admin/businesses/': typeof SuperSuperAdminBusinessesIndexRoute
  '/super-admin/packages/': typeof SuperSuperAdminPackagesIndexRoute
  '/super-admin/settings/': typeof SuperSuperAdminSettingsIndexRoute
  '/super-admin/businesses/$id/edit': typeof SuperSuperAdminBusinessesIdEditRoute
  '/super-admin/packages/$id/edit': typeof SuperSuperAdminPackagesIdEditRoute
  '/super-admin/settings/payments/mpesa': typeof SuperSuperAdminSettingsPaymentsMpesaRoute
  '/super-admin/settings/payments/paystack': typeof SuperSuperAdminSettingsPaymentsPaystackRoute
  '/super-admin/businesses/$id/': typeof SuperSuperAdminBusinessesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/banking': typeof AppBankingRoute
  '/barcode-mapping': typeof AppBarcodeMappingRoute
  '/chart-of-accounts': typeof AppChartOfAccountsRoute
  '/customers': typeof AppCustomersRoute
  '/expenses': typeof AppExpensesRoute
  '/hr': typeof AppHrRoute
  '/inventory': typeof AppInventoryRoute
  '/journal-entries': typeof AppJournalEntriesRoute
  '/notifications': typeof AppNotificationsRoute
  '/pos': typeof AppPosRoute
  '/products': typeof AppProductsRoute
  '/profile': typeof AppProfileRoute
  '/reports': typeof AppReportsRoute
  '/roles': typeof AppRolesRoute
  '/sales': typeof AppSalesRoute
  '/settings': typeof AppSettingsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/tax-compliance': typeof AppTaxComplianceRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/purchases/new': typeof AppPurchasesNewRoute
  '/super-admin/activity': typeof SuperSuperAdminActivityRoute
  '/super-admin/landing': typeof SuperSuperAdminLandingRoute
  '/super-admin/modules': typeof SuperSuperAdminModulesRoute
  '/super-admin/notifications': typeof SuperSuperAdminNotificationsRoute
  '/super-admin/payments': typeof SuperSuperAdminPaymentsRoute
  '/super-admin/subscriptions': typeof SuperSuperAdminSubscriptionsRoute
  '/super-admin/tenant-approvals': typeof SuperSuperAdminTenantApprovalsRoute
  '/super-admin/users': typeof SuperSuperAdminUsersRoute
  '/purchases': typeof AppPurchasesIndexRoute
  '/super-admin': typeof SuperSuperAdminIndexRoute
  '/purchases/$id/edit': typeof AppPurchasesIdEditRoute
  '/super-admin/cms/cta': typeof SuperSuperAdminCmsCtaRoute
  '/super-admin/cms/faq': typeof SuperSuperAdminCmsFaqRoute
  '/super-admin/cms/features': typeof SuperSuperAdminCmsFeaturesRoute
  '/super-admin/cms/hero': typeof SuperSuperAdminCmsHeroRoute
  '/super-admin/cms/how-it-works': typeof SuperSuperAdminCmsHowItWorksRoute
  '/super-admin/cms/pricing': typeof SuperSuperAdminCmsPricingRoute
  '/super-admin/cms/stats': typeof SuperSuperAdminCmsStatsRoute
  '/super-admin/cms/testimonials': typeof SuperSuperAdminCmsTestimonialsRoute
  '/super-admin/packages/new': typeof SuperSuperAdminPackagesNewRoute
  '/super-admin/businesses': typeof SuperSuperAdminBusinessesIndexRoute
  '/super-admin/packages': typeof SuperSuperAdminPackagesIndexRoute
  '/super-admin/settings': typeof SuperSuperAdminSettingsIndexRoute
  '/super-admin/businesses/$id/edit': typeof SuperSuperAdminBusinessesIdEditRoute
  '/super-admin/packages/$id/edit': typeof SuperSuperAdminPackagesIdEditRoute
  '/super-admin/settings/payments/mpesa': typeof SuperSuperAdminSettingsPaymentsMpesaRoute
  '/super-admin/settings/payments/paystack': typeof SuperSuperAdminSettingsPaymentsPaystackRoute
  '/super-admin/businesses/$id': typeof SuperSuperAdminBusinessesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_super': typeof SuperRouteWithChildren
  '/auth': typeof AuthRoute
  '/landing': typeof LandingRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/_app/banking': typeof AppBankingRoute
  '/_app/barcode-mapping': typeof AppBarcodeMappingRoute
  '/_app/chart-of-accounts': typeof AppChartOfAccountsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/hr': typeof AppHrRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/journal-entries': typeof AppJournalEntriesRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/products': typeof AppProductsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/roles': typeof AppRolesRoute
  '/_app/sales': typeof AppSalesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/tax-compliance': typeof AppTaxComplianceRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/super-admin/login': typeof SuperAdminLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/purchases/new': typeof AppPurchasesNewRoute
  '/_super/super-admin/activity': typeof SuperSuperAdminActivityRoute
  '/_super/super-admin/landing': typeof SuperSuperAdminLandingRoute
  '/_super/super-admin/modules': typeof SuperSuperAdminModulesRoute
  '/_super/super-admin/notifications': typeof SuperSuperAdminNotificationsRoute
  '/_super/super-admin/payments': typeof SuperSuperAdminPaymentsRoute
  '/_super/super-admin/subscriptions': typeof SuperSuperAdminSubscriptionsRoute
  '/_super/super-admin/tenant-approvals': typeof SuperSuperAdminTenantApprovalsRoute
  '/_super/super-admin/users': typeof SuperSuperAdminUsersRoute
  '/_app/purchases/': typeof AppPurchasesIndexRoute
  '/_super/super-admin/': typeof SuperSuperAdminIndexRoute
  '/_app/purchases/$id/edit': typeof AppPurchasesIdEditRoute
  '/_super/super-admin/cms/cta': typeof SuperSuperAdminCmsCtaRoute
  '/_super/super-admin/cms/faq': typeof SuperSuperAdminCmsFaqRoute
  '/_super/super-admin/cms/features': typeof SuperSuperAdminCmsFeaturesRoute
  '/_super/super-admin/cms/hero': typeof SuperSuperAdminCmsHeroRoute
  '/_super/super-admin/cms/how-it-works': typeof SuperSuperAdminCmsHowItWorksRoute
  '/_super/super-admin/cms/pricing': typeof SuperSuperAdminCmsPricingRoute
  '/_super/super-admin/cms/stats': typeof SuperSuperAdminCmsStatsRoute
  '/_super/super-admin/cms/testimonials': typeof SuperSuperAdminCmsTestimonialsRoute
  '/_super/super-admin/packages/new': typeof SuperSuperAdminPackagesNewRoute
  '/_super/super-admin/businesses/': typeof SuperSuperAdminBusinessesIndexRoute
  '/_super/super-admin/packages/': typeof SuperSuperAdminPackagesIndexRoute
  '/_super/super-admin/settings/': typeof SuperSuperAdminSettingsIndexRoute
  '/_super/super-admin/businesses/$id/edit': typeof SuperSuperAdminBusinessesIdEditRoute
  '/_super/super-admin/packages/$id/edit': typeof SuperSuperAdminPackagesIdEditRoute
  '/_super/super-admin/settings/payments/mpesa': typeof SuperSuperAdminSettingsPaymentsMpesaRoute
  '/_super/super-admin/settings/payments/paystack': typeof SuperSuperAdminSettingsPaymentsPaystackRoute
  '/_super/super-admin/businesses/$id/': typeof SuperSuperAdminBusinessesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/landing'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sign-in'
    | '/terms'
    | '/banking'
    | '/barcode-mapping'
    | '/chart-of-accounts'
    | '/customers'
    | '/expenses'
    | '/hr'
    | '/inventory'
    | '/journal-entries'
    | '/notifications'
    | '/pos'
    | '/products'
    | '/profile'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/tax-compliance'
    | '/invoice/$id'
    | '/super-admin/login'
    | '/purchases/new'
    | '/super-admin/activity'
    | '/super-admin/landing'
    | '/super-admin/modules'
    | '/super-admin/notifications'
    | '/super-admin/payments'
    | '/super-admin/subscriptions'
    | '/super-admin/tenant-approvals'
    | '/super-admin/users'
    | '/purchases/'
    | '/super-admin/'
    | '/purchases/$id/edit'
    | '/super-admin/cms/cta'
    | '/super-admin/cms/faq'
    | '/super-admin/cms/features'
    | '/super-admin/cms/hero'
    | '/super-admin/cms/how-it-works'
    | '/super-admin/cms/pricing'
    | '/super-admin/cms/stats'
    | '/super-admin/cms/testimonials'
    | '/super-admin/packages/new'
    | '/super-admin/businesses/'
    | '/super-admin/packages/'
    | '/super-admin/settings/'
    | '/super-admin/businesses/$id/edit'
    | '/super-admin/packages/$id/edit'
    | '/super-admin/settings/payments/mpesa'
    | '/super-admin/settings/payments/paystack'
    | '/super-admin/businesses/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/landing'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sign-in'
    | '/terms'
    | '/banking'
    | '/barcode-mapping'
    | '/chart-of-accounts'
    | '/customers'
    | '/expenses'
    | '/hr'
    | '/inventory'
    | '/journal-entries'
    | '/notifications'
    | '/pos'
    | '/products'
    | '/profile'
    | '/reports'
    | '/roles'
    | '/sales'
    | '/settings'
    | '/suppliers'
    | '/tax-compliance'
    | '/invoice/$id'
    | '/super-admin/login'
    | '/purchases/new'
    | '/super-admin/activity'
    | '/super-admin/landing'
    | '/super-admin/modules'
    | '/super-admin/notifications'
    | '/super-admin/payments'
    | '/super-admin/subscriptions'
    | '/super-admin/tenant-approvals'
    | '/super-admin/users'
    | '/purchases'
    | '/super-admin'
    | '/purchases/$id/edit'
    | '/super-admin/cms/cta'
    | '/super-admin/cms/faq'
    | '/super-admin/cms/features'
    | '/super-admin/cms/hero'
    | '/super-admin/cms/how-it-works'
    | '/super-admin/cms/pricing'
    | '/super-admin/cms/stats'
    | '/super-admin/cms/testimonials'
    | '/super-admin/packages/new'
    | '/super-admin/businesses'
    | '/super-admin/packages'
    | '/super-admin/settings'
    | '/super-admin/businesses/$id/edit'
    | '/super-admin/packages/$id/edit'
    | '/super-admin/settings/payments/mpesa'
    | '/super-admin/settings/payments/paystack'
    | '/super-admin/businesses/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_super'
    | '/auth'
    | '/landing'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/sign-in'
    | '/terms'
    | '/_app/banking'
    | '/_app/barcode-mapping'
    | '/_app/chart-of-accounts'
    | '/_app/customers'
    | '/_app/expenses'
    | '/_app/hr'
    | '/_app/inventory'
    | '/_app/journal-entries'
    | '/_app/notifications'
    | '/_app/pos'
    | '/_app/products'
    | '/_app/profile'
    | '/_app/reports'
    | '/_app/roles'
    | '/_app/sales'
    | '/_app/settings'
    | '/_app/suppliers'
    | '/_app/tax-compliance'
    | '/invoice/$id'
    | '/super-admin/login'
    | '/_app/'
    | '/_app/purchases/new'
    | '/_super/super-admin/activity'
    | '/_super/super-admin/landing'
    | '/_super/super-admin/modules'
    | '/_super/super-admin/notifications'
    | '/_super/super-admin/payments'
    | '/_super/super-admin/subscriptions'
    | '/_super/super-admin/tenant-approvals'
    | '/_super/super-admin/users'
    | '/_app/purchases/'
    | '/_super/super-admin/'
    | '/_app/purchases/$id/edit'
    | '/_super/super-admin/cms/cta'
    | '/_super/super-admin/cms/faq'
    | '/_super/super-admin/cms/features'
    | '/_super/super-admin/cms/hero'
    | '/_super/super-admin/cms/how-it-works'
    | '/_super/super-admin/cms/pricing'
    | '/_super/super-admin/cms/stats'
    | '/_super/super-admin/cms/testimonials'
    | '/_super/super-admin/packages/new'
    | '/_super/super-admin/businesses/'
    | '/_super/super-admin/packages/'
    | '/_super/super-admin/settings/'
    | '/_super/super-admin/businesses/$id/edit'
    | '/_super/super-admin/packages/$id/edit'
    | '/_super/super-admin/settings/payments/mpesa'
    | '/_super/super-admin/settings/payments/paystack'
    | '/_super/super-admin/businesses/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SuperRoute: typeof SuperRouteWithChildren
  AuthRoute: typeof AuthRoute
  LandingRoute: typeof LandingRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  SuperAdminLoginRoute: typeof SuperAdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_super': {
      id: '/_super'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/banking': {
      id: '/_app/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof AppBankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/barcode-mapping': {
      id: '/_app/barcode-mapping'
      path: '/barcode-mapping'
      fullPath: '/barcode-mapping'
      preLoaderRoute: typeof AppBarcodeMappingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chart-of-accounts': {
      id: '/_app/chart-of-accounts'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts'
      preLoaderRoute: typeof AppChartOfAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hr': {
      id: '/_app/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AppHrRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal-entries': {
      id: '/_app/journal-entries'
      path: '/journal-entries'
      fullPath: '/journal-entries'
      preLoaderRoute: typeof AppJournalEntriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products': {
      id: '/_app/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/roles': {
      id: '/_app/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AppRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales': {
      id: '/_app/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AppSalesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tax-compliance': {
      id: '/_app/tax-compliance'
      path: '/tax-compliance'
      fullPath: '/tax-compliance'
      preLoaderRoute: typeof AppTaxComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/login': {
      id: '/super-admin/login'
      path: '/super-admin/login'
      fullPath: '/super-admin/login'
      preLoaderRoute: typeof SuperAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/purchases/': {
      id: '/_app/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AppPurchasesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases/new': {
      id: '/_app/purchases/new'
      path: '/purchases/new'
      fullPath: '/purchases/new'
      preLoaderRoute: typeof AppPurchasesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_super/super-admin/': {
      id: '/_super/super-admin/'
      path: '/super-admin'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperSuperAdminIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/activity': {
      id: '/_super/super-admin/activity'
      path: '/super-admin/activity'
      fullPath: '/super-admin/activity'
      preLoaderRoute: typeof SuperSuperAdminActivityRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/landing': {
      id: '/_super/super-admin/landing'
      path: '/super-admin/landing'
      fullPath: '/super-admin/landing'
      preLoaderRoute: typeof SuperSuperAdminLandingRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/modules': {
      id: '/_super/super-admin/modules'
      path: '/super-admin/modules'
      fullPath: '/super-admin/modules'
      preLoaderRoute: typeof SuperSuperAdminModulesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/notifications': {
      id: '/_super/super-admin/notifications'
      path: '/super-admin/notifications'
      fullPath: '/super-admin/notifications'
      preLoaderRoute: typeof SuperSuperAdminNotificationsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/payments': {
      id: '/_super/super-admin/payments'
      path: '/super-admin/payments'
      fullPath: '/super-admin/payments'
      preLoaderRoute: typeof SuperSuperAdminPaymentsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/subscriptions': {
      id: '/_super/super-admin/subscriptions'
      path: '/super-admin/subscriptions'
      fullPath: '/super-admin/subscriptions'
      preLoaderRoute: typeof SuperSuperAdminSubscriptionsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/tenant-approvals': {
      id: '/_super/super-admin/tenant-approvals'
      path: '/super-admin/tenant-approvals'
      fullPath: '/super-admin/tenant-approvals'
      preLoaderRoute: typeof SuperSuperAdminTenantApprovalsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/users': {
      id: '/_super/super-admin/users'
      path: '/super-admin/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperSuperAdminUsersRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_app/purchases/$id/edit': {
      id: '/_app/purchases/$id/edit'
      path: '/purchases/$id/edit'
      fullPath: '/purchases/$id/edit'
      preLoaderRoute: typeof AppPurchasesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_super/super-admin/businesses/': {
      id: '/_super/super-admin/businesses/'
      path: '/super-admin/businesses'
      fullPath: '/super-admin/businesses/'
      preLoaderRoute: typeof SuperSuperAdminBusinessesIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/cms/cta': {
      id: '/_super/super-admin/cms/cta'
      path: '/super-admin/cms/cta'
      fullPath: '/super-admin/cms/cta'
      preLoaderRoute: typeof SuperSuperAdminCmsCtaRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/cms/faq': {
      id: '/_super/super-admin/cms/faq'
      path: '/super-admin/cms/faq'
      fullPath: '/super-admin/cms/faq'
      preLoaderRoute: typeof SuperSuperAdminCmsFaqRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/cms/features': {
      id: '/_super/super-admin/cms/features'
      path: '/super-admin/cms/features'
      fullPath: '/super-admin/cms/features'
      preLoaderRoute: typeof SuperSuperAdminCmsFeaturesRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/cms/hero': {
      id: '/_super/super-admin/cms/hero'
      path: '/super-admin/cms/hero'
      fullPath: '/super-admin/cms/hero'
      preLoaderRoute: typeof SuperSuperAdminCmsHeroRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/cms/how-it-works': {
      id: '/_super/super-admin/cms/how-it-works'
      path: '/super-admin/cms/how-it-works'
      fullPath: '/super-admin/cms/how-it-works'
      preLoaderRoute: typeof SuperSuperAdminCmsHowItWorksRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/cms/pricing': {
      id: '/_super/super-admin/cms/pricing'
      path: '/super-admin/cms/pricing'
      fullPath: '/super-admin/cms/pricing'
      preLoaderRoute: typeof SuperSuperAdminCmsPricingRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/cms/stats': {
      id: '/_super/super-admin/cms/stats'
      path: '/super-admin/cms/stats'
      fullPath: '/super-admin/cms/stats'
      preLoaderRoute: typeof SuperSuperAdminCmsStatsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/cms/testimonials': {
      id: '/_super/super-admin/cms/testimonials'
      path: '/super-admin/cms/testimonials'
      fullPath: '/super-admin/cms/testimonials'
      preLoaderRoute: typeof SuperSuperAdminCmsTestimonialsRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/packages/': {
      id: '/_super/super-admin/packages/'
      path: '/super-admin/packages'
      fullPath: '/super-admin/packages/'
      preLoaderRoute: typeof SuperSuperAdminPackagesIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/packages/new': {
      id: '/_super/super-admin/packages/new'
      path: '/super-admin/packages/new'
      fullPath: '/super-admin/packages/new'
      preLoaderRoute: typeof SuperSuperAdminPackagesNewRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/settings/': {
      id: '/_super/super-admin/settings/'
      path: '/super-admin/settings'
      fullPath: '/super-admin/settings/'
      preLoaderRoute: typeof SuperSuperAdminSettingsIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/businesses/$id/': {
      id: '/_super/super-admin/businesses/$id/'
      path: '/super-admin/businesses/$id'
      fullPath: '/super-admin/businesses/$id/'
      preLoaderRoute: typeof SuperSuperAdminBusinessesIdIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/businesses/$id/edit': {
      id: '/_super/super-admin/businesses/$id/edit'
      path: '/super-admin/businesses/$id/edit'
      fullPath: '/super-admin/businesses/$id/edit'
      preLoaderRoute: typeof SuperSuperAdminBusinessesIdEditRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/packages/$id/edit': {
      id: '/_super/super-admin/packages/$id/edit'
      path: '/super-admin/packages/$id/edit'
      fullPath: '/super-admin/packages/$id/edit'
      preLoaderRoute: typeof SuperSuperAdminPackagesIdEditRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/settings/payments/mpesa': {
      id: '/_super/super-admin/settings/payments/mpesa'
      path: '/super-admin/settings/payments/mpesa'
      fullPath: '/super-admin/settings/payments/mpesa'
      preLoaderRoute: typeof SuperSuperAdminSettingsPaymentsMpesaRouteImport
      parentRoute: typeof SuperRoute
    }
    '/_super/super-admin/settings/payments/paystack': {
      id: '/_super/super-admin/settings/payments/paystack'
      path: '/super-admin/settings/payments/paystack'
      fullPath: '/super-admin/settings/payments/paystack'
      preLoaderRoute: typeof SuperSuperAdminSettingsPaymentsPaystackRouteImport
      parentRoute: typeof SuperRoute
    }
  }
}

interface AppRouteChildren {
  AppBankingRoute: typeof AppBankingRoute
  AppBarcodeMappingRoute: typeof AppBarcodeMappingRoute
  AppChartOfAccountsRoute: typeof AppChartOfAccountsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppHrRoute: typeof AppHrRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppJournalEntriesRoute: typeof AppJournalEntriesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPosRoute: typeof AppPosRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRolesRoute: typeof AppRolesRoute
  AppSalesRoute: typeof AppSalesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTaxComplianceRoute: typeof AppTaxComplianceRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPurchasesNewRoute: typeof AppPurchasesNewRoute
  AppPurchasesIndexRoute: typeof AppPurchasesIndexRoute
  AppPurchasesIdEditRoute: typeof AppPurchasesIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBankingRoute: AppBankingRoute,
  AppBarcodeMappingRoute: AppBarcodeMappingRoute,
  AppChartOfAccountsRoute: AppChartOfAccountsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppHrRoute: AppHrRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppJournalEntriesRoute: AppJournalEntriesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPosRoute: AppPosRoute,
  AppProductsRoute: AppProductsRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportsRoute: AppReportsRoute,
  AppRolesRoute: AppRolesRoute,
  AppSalesRoute: AppSalesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTaxComplianceRoute: AppTaxComplianceRoute,
  AppIndexRoute: AppIndexRoute,
  AppPurchasesNewRoute: AppPurchasesNewRoute,
  AppPurchasesIndexRoute: AppPurchasesIndexRoute,
  AppPurchasesIdEditRoute: AppPurchasesIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SuperRouteChildren {
  SuperSuperAdminActivityRoute: typeof SuperSuperAdminActivityRoute
  SuperSuperAdminLandingRoute: typeof SuperSuperAdminLandingRoute
  SuperSuperAdminModulesRoute: typeof SuperSuperAdminModulesRoute
  SuperSuperAdminNotificationsRoute: typeof SuperSuperAdminNotificationsRoute
  SuperSuperAdminPaymentsRoute: typeof SuperSuperAdminPaymentsRoute
  SuperSuperAdminSubscriptionsRoute: typeof SuperSuperAdminSubscriptionsRoute
  SuperSuperAdminTenantApprovalsRoute: typeof SuperSuperAdminTenantApprovalsRoute
  SuperSuperAdminUsersRoute: typeof SuperSuperAdminUsersRoute
  SuperSuperAdminIndexRoute: typeof SuperSuperAdminIndexRoute
  SuperSuperAdminCmsCtaRoute: typeof SuperSuperAdminCmsCtaRoute
  SuperSuperAdminCmsFaqRoute: typeof SuperSuperAdminCmsFaqRoute
  SuperSuperAdminCmsFeaturesRoute: typeof SuperSuperAdminCmsFeaturesRoute
  SuperSuperAdminCmsHeroRoute: typeof SuperSuperAdminCmsHeroRoute
  SuperSuperAdminCmsHowItWorksRoute: typeof SuperSuperAdminCmsHowItWorksRoute
  SuperSuperAdminCmsPricingRoute: typeof SuperSuperAdminCmsPricingRoute
  SuperSuperAdminCmsStatsRoute: typeof SuperSuperAdminCmsStatsRoute
  SuperSuperAdminCmsTestimonialsRoute: typeof SuperSuperAdminCmsTestimonialsRoute
  SuperSuperAdminPackagesNewRoute: typeof SuperSuperAdminPackagesNewRoute
  SuperSuperAdminBusinessesIndexRoute: typeof SuperSuperAdminBusinessesIndexRoute
  SuperSuperAdminPackagesIndexRoute: typeof SuperSuperAdminPackagesIndexRoute
  SuperSuperAdminSettingsIndexRoute: typeof SuperSuperAdminSettingsIndexRoute
  SuperSuperAdminBusinessesIdEditRoute: typeof SuperSuperAdminBusinessesIdEditRoute
  SuperSuperAdminPackagesIdEditRoute: typeof SuperSuperAdminPackagesIdEditRoute
  SuperSuperAdminSettingsPaymentsMpesaRoute: typeof SuperSuperAdminSettingsPaymentsMpesaRoute
  SuperSuperAdminSettingsPaymentsPaystackRoute: typeof SuperSuperAdminSettingsPaymentsPaystackRoute
  SuperSuperAdminBusinessesIdIndexRoute: typeof SuperSuperAdminBusinessesIdIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperSuperAdminActivityRoute: SuperSuperAdminActivityRoute,
  SuperSuperAdminLandingRoute: SuperSuperAdminLandingRoute,
  SuperSuperAdminModulesRoute: SuperSuperAdminModulesRoute,
  SuperSuperAdminNotificationsRoute: SuperSuperAdminNotificationsRoute,
  SuperSuperAdminPaymentsRoute: SuperSuperAdminPaymentsRoute,
  SuperSuperAdminSubscriptionsRoute: SuperSuperAdminSubscriptionsRoute,
  SuperSuperAdminTenantApprovalsRoute: SuperSuperAdminTenantApprovalsRoute,
  SuperSuperAdminUsersRoute: SuperSuperAdminUsersRoute,
  SuperSuperAdminIndexRoute: SuperSuperAdminIndexRoute,
  SuperSuperAdminCmsCtaRoute: SuperSuperAdminCmsCtaRoute,
  SuperSuperAdminCmsFaqRoute: SuperSuperAdminCmsFaqRoute,
  SuperSuperAdminCmsFeaturesRoute: SuperSuperAdminCmsFeaturesRoute,
  SuperSuperAdminCmsHeroRoute: SuperSuperAdminCmsHeroRoute,
  SuperSuperAdminCmsHowItWorksRoute: SuperSuperAdminCmsHowItWorksRoute,
  SuperSuperAdminCmsPricingRoute: SuperSuperAdminCmsPricingRoute,
  SuperSuperAdminCmsStatsRoute: SuperSuperAdminCmsStatsRoute,
  SuperSuperAdminCmsTestimonialsRoute: SuperSuperAdminCmsTestimonialsRoute,
  SuperSuperAdminPackagesNewRoute: SuperSuperAdminPackagesNewRoute,
  SuperSuperAdminBusinessesIndexRoute: SuperSuperAdminBusinessesIndexRoute,
  SuperSuperAdminPackagesIndexRoute: SuperSuperAdminPackagesIndexRoute,
  SuperSuperAdminSettingsIndexRoute: SuperSuperAdminSettingsIndexRoute,
  SuperSuperAdminBusinessesIdEditRoute: SuperSuperAdminBusinessesIdEditRoute,
  SuperSuperAdminPackagesIdEditRoute: SuperSuperAdminPackagesIdEditRoute,
  SuperSuperAdminSettingsPaymentsMpesaRoute:
    SuperSuperAdminSettingsPaymentsMpesaRoute,
  SuperSuperAdminSettingsPaymentsPaystackRoute:
    SuperSuperAdminSettingsPaymentsPaystackRoute,
  SuperSuperAdminBusinessesIdIndexRoute: SuperSuperAdminBusinessesIdIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SuperRoute: SuperRouteWithChildren,
  AuthRoute: AuthRoute,
  LandingRoute: LandingRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  SuperAdminLoginRoute: SuperAdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
